import { Category, GrowthItem, ItemType, BlogPost, ContentType } from './types';

// Sample Courses Data
export const STATIC_COURSES: GrowthItem[] = [
  {
    id: 'course-amr-01',
    slug: 'affiliate-marketing-revolutie',
    title: 'Affiliate Marketing Revolutie',
    description: 'Leer hoe je een winstgevend affiliate business opbouwt. Van niche selectie tot SEO en conversiemethodes.',
    seoDescription: 'Complete cursus affiliate marketing voor beginners en gevorderden. Bouw je eigen passief inkomen online.',
    seoTitle: 'Affiliate Marketing Revolutie Cursus Review 2024',
    seoKeywords: ['affiliate marketing cursus', 'passief inkomen', 'online geld verdienen'],
    category: Category.MARKETING,
    type: ItemType.COURSE,
    contentType: ContentType.CURSUS,
    priceLabel: '€497 eenmalig',
    rating: 4.8,
    provider: 'IMU',
    executiveSummary: "De Affiliate Marketing Revolutie is dé cursus voor iedereen die serieus wil starten met affiliate marketing. De stapsgewijze aanpak maakt het toegankelijk voor complete beginners.",
    scores: { usability: 9.0, priceValue: 8.5, features: 8.5, support: 9.0 },
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1280&q=80',
    galleryImages: ['https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&w=1200&q=80'],
    affiliateLink: 'https://www.imu.nl/amr',
    tags: ['affiliate', 'seo', 'passief inkomen', 'online marketing', 'cursus'],
    pros: ['Stapsgewijze aanpak voor beginners', 'Focus op duurzame SEO-methodes', 'Actieve community en support', 'Regelmatige updates'],
    cons: ['Relatief hoge eenmalige investering', 'Vereist tijd en consistentie'],
    features: ['50+ video lessen', 'Niche Research Module', 'Keyword Strategie Training', 'Lifetime Access'],
    reviewContent: {
      introduction: "In een wereld vol 'snel rijk worden' schema's is de Affiliate Marketing Revolutie een verademing.",
      featuresAnalysis: "De cursus is opgebouwd uit logische modules die je van nul naar een werkende affiliate site brengen.",
      easeOfUse: "De video's zijn helder en goed te volgen. Zelfs als je nog nooit een website hebt gebouwd, kun je aan de slag.",
      supportQuality: "Via de community kun je vragen stellen aan zowel de makers als medecursisten.",
      verdict: "Als je bereid bent tijd en moeite te investeren, is de AMR een van de beste investeringen die je kunt doen."
    },
    specifications: [{ label: 'Modules', value: '12' }, { label: 'Video Lessen', value: '50+' }, { label: 'Toegang', value: 'Lifetime' }, { label: 'Taal', value: 'Nederlands' }],
    pricingTiers: [{ name: 'Standaard', price: '€497', features: ['Volledige cursus', 'Community toegang', 'Lifetime updates'] }],
    reviewAuthor: { name: 'Sander de Vries', role: 'Marketing Expert', avatarUrl: 'https://ui-avatars.com/api/?name=Sander+de+Vries&background=0D8ABC&color=fff', summary: 'Sander heeft jarenlange ervaring met affiliate marketing.' },
    targetAudience: ['Beginners die willen starten met affiliate marketing', 'Bloggers die hun website willen monetizen'],
    bestFor: ['Mensen die bereid zijn langetermijn te denken', 'Content creators met schrijftalent'],
    notFor: ['Mensen die snel rijk willen worden'],
    alternatives: ['SEM Rush Academy', 'Income School'],
    faq: [{ question: 'Heb ik technische kennis nodig?', answer: 'Nee, de cursus leert je alles vanaf de basis.' }],
    updatedAt: '20 november 2024'
  },
  {
    id: 'course-python-01',
    slug: 'python-voor-beginners',
    title: 'Python Programmeren voor Beginners',
    description: 'Leer Python programmeren vanaf nul. Inclusief praktische projecten en real-world toepassingen.',
    seoDescription: 'Complete Python cursus voor beginners. Leer programmeren met praktische projecten.',
    category: Category.DEVELOPMENT,
    type: ItemType.COURSE,
    contentType: ContentType.CURSUS,
    priceLabel: '€199 eenmalig',
    rating: 4.7,
    provider: 'Codemy',
    executiveSummary: "Deze Python cursus is perfect voor absolute beginners. De didactiek is helder.",
    scores: { usability: 9.5, priceValue: 9.0, features: 8.0, support: 8.5 },
    imageUrl: 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?auto=format&fit=crop&w=1280&q=80',
    affiliateLink: 'https://www.codemy.nl/python',
    tags: ['python', 'programmeren', 'coding', 'beginners', 'development'],
    pros: ['Zeer duidelijke uitleg', 'Praktische projecten', 'Betaalbare prijs', 'Nederlandstalig'],
    cons: ['Minder diepgaand voor gevorderden'],
    features: ['40+ video lessen', '10 praktijkprojecten', 'Downloadbare code', 'Oefeningen'],
    specifications: [{ label: 'Niveau', value: 'Beginner' }, { label: 'Duur', value: '~20 uur' }, { label: 'Projecten', value: '10' }],
    targetAudience: ['Studenten', 'Professionals die Python willen leren'],
    faq: [{ question: 'Welke voorkennis heb ik nodig?', answer: 'Geen! De cursus begint bij het begin.' }],
    updatedAt: '15 november 2024'
  },
  {
    id: 'course-foto-01',
    slug: 'fotograferen-als-een-pro',
    title: 'Fotograferen als een Pro',
    description: 'Van automatisch naar handmatig: leer de geheimen van professionele fotografie.',
    seoDescription: 'Complete fotografiecursus: van automatische instellingen naar professionele fotos.',
    category: Category.DESIGN,
    type: ItemType.COURSE,
    contentType: ContentType.CURSUS,
    priceLabel: '€349',
    rating: 4.9,
    provider: 'FotoAcademie',
    imageUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1280&q=80',
    affiliateLink: 'https://www.fotoacademie.nl/pro',
    tags: ['fotografie', 'camera', 'lightroom', 'creatief', 'cursus'],
    pros: ['Praktijkgerichte aanpak', 'Feedback van fotografen', 'Inclusief Lightroom module'],
    cons: ['Vereist een DSLR of mirrorless camera'],
    features: ['Belichting theorie', 'Compositie technieken', 'Lightroom editing', 'Portfolio opbouw'],
    targetAudience: ['Hobbyfotografen', 'Mensen met een nieuwe camera'],
    updatedAt: '10 november 2024'
  }
];

// Sample Tools Data
export const STATIC_TOOLS: GrowthItem[] = [
  {
    id: 'pnp-01',
    slug: 'plug-and-pay',
    title: 'Plug & Pay',
    description: 'De snelste manier om meer omzet te halen uit je website. Kant-en-klare betaalpaginas en upsells die converteren.',
    seoDescription: 'Review van Plug & Pay: Is dit de beste checkout software voor Nederlandse ondernemers?',
    category: Category.MARKETING,
    type: ItemType.APP,
    contentType: ContentType.TOOL,
    priceLabel: 'Vanaf €15/mnd',
    rating: 4.9,
    provider: 'IMU',
    executiveSummary: "Plug & Pay is niet zomaar checkout-software; het is een conversie-machine. Voor Nederlandse ondernemers is er geen betere optie.",
    scores: { usability: 9.5, priceValue: 8.0, features: 9.0, support: 9.0 },
    imageUrl: 'https://media-01.imu.nl/storage/plugandpay.nl/20245/verkooppagina-plugandpay-1350x1350-3.png',
    galleryImages: ['https://images.unsplash.com/photo-1556742049-0cfed4f7a07d?auto=format&fit=crop&w=1200&q=80'],
    affiliateLink: 'https://start.plugandpay.nl/r?id=pch21z5F',
    tags: ['sales', 'checkout', 'business', 'conversie', 'marketing'],
    pros: ['Binnen 5 minuten een werkende betaalpagina', 'Bewezen templates', 'Ingebouwde upsell modules', 'Mollie integratie'],
    cons: ['Geavanceerde features vereisen duurder pakket', 'Design opties beperkt'],
    features: ['1-click upsells', 'Abonnementen beheer', 'Facturatie automatisering', 'A/B Split testing'],
    reviewContent: {
      introduction: "Als ondernemer wil je je focussen op je product en je klanten, niet op ingewikkelde betaalsystemen.",
      featuresAnalysis: "De kracht van Plug & Pay zit in de focus op conversie. De Kassakoopjes zijn geniaal.",
      easeOfUse: "Je hebt absoluut geen technische kennis nodig.",
      supportQuality: "De support is volledig Nederlands en zeer kundig.",
      verdict: "Plug & Pay is de beste checkout software voor Nederlandse ondernemers."
    },
    specifications: [{ label: 'Type', value: 'SaaS' }, { label: 'Taal', value: 'Nederlands' }, { label: 'Betalingen', value: 'Mollie' }],
    pricingTiers: [{ name: 'Lite', price: '€15/mnd', features: ['Tot €2.500 omzet/mnd'] }, { name: 'Premium', price: '€59/mnd', features: ['Onbeperkte omzet'] }],
    reviewAuthor: { name: 'Sander de Vries', role: 'Senior Marketeer', avatarUrl: 'https://ui-avatars.com/api/?name=Sander&background=0D8ABC&color=fff', summary: 'Sander test al 10 jaar e-commerce software.' },
    targetAudience: ['Coaches en trainers', 'E-commerce ondernemers', 'Start-ups'],
    bestFor: ['Verkopers van digitale producten', 'Coaches met abonnementen'],
    notFor: ['Webshops met duizenden fysieke producten'],
    alternatives: ['Shopify', 'WooCommerce'],
    faq: [{ question: 'Werkt Plug & Pay met iDeal?', answer: 'Ja, via Mollie.' }],
    updatedAt: '14 oktober 2024'
  },
  {
    id: 'heijsen-01',
    slug: 'heijsen-webhosting',
    title: 'Heijsen Webhosting',
    description: 'Razendsnelle en betrouwbare webhosting voor Nederlandse ondernemers. Inclusief gratis SSL.',
    seoDescription: 'Review van Heijsen Webhosting: De beste keuze voor MKB en ZZP?',
    category: Category.DEVELOPMENT,
    type: ItemType.PLATFORM,
    contentType: ContentType.TOOL,
    priceLabel: 'Vanaf €5/mnd',
    rating: 4.8,
    provider: 'Heijsen',
    executiveSummary: "Heijsen Webhosting is een toonbeeld van Nederlandse kwaliteit. NVMe-opslag en LiteSpeed maken het ideaal.",
    scores: { usability: 9.0, priceValue: 8.0, features: 8.5, support: 9.5 },
    imageUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=1280&q=80',
    affiliateLink: 'https://www.heijsen.nl/',
    tags: ['webhosting', 'wordpress', 'mkb', 'website', 'snelheid'],
    pros: ['NVMe SSD opslag', 'LiteSpeed webserver', 'Nederlandse helpdesk', 'Dagelijkse backups'],
    cons: ['Iets duurder dan budget-providers'],
    features: ['Gratis SSL', 'DirectAdmin', '1-klik WordPress', 'Imunify360'],
    specifications: [{ label: 'Opslag', value: 'NVMe SSD' }, { label: 'Panel', value: 'DirectAdmin' }],
    pricingTiers: [{ name: 'Start', price: '€5/mnd', features: ['1 Website', '10GB'] }, { name: 'Plus', price: '€10/mnd', features: ['5 Websites'] }],
    targetAudience: ['ZZPers en MKBers', 'Webdesigners', 'WordPress gebruikers'],
    faq: [{ question: 'Kan ik mijn website verhuizen?', answer: 'Ja, gratis verhuisservice.' }],
    updatedAt: '15 oktober 2024'
  },
  {
    id: 'huddle-01',
    slug: 'the-huddle',
    title: 'The Huddle',
    description: 'Bouw je eigen community en e-learning platform. Alles-in-een software voor cursussen en lidmaatschappen.',
    seoDescription: 'The Huddle Review 2024: Bouw je eigen community en e-learning platform.',
    category: Category.PRODUCTIVITY,
    type: ItemType.PLATFORM,
    contentType: ContentType.TOOL,
    priceLabel: 'Vanaf €19/mnd',
    rating: 4.7,
    provider: 'IMU',
    executiveSummary: "The Huddle combineert een online cursus platform met een social media feed. Het lost het probleem op van dode cursussen.",
    scores: { usability: 9.0, priceValue: 8.5, features: 8.5, support: 9.0 },
    imageUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1280&q=80',
    affiliateLink: 'https://checkout.thehuddle.nl/r?id=X2nJGep5',
    tags: ['community', 'cursus platform', 'membership', 'coaching', 'e-learning'],
    pros: ['Community en Cursus geintegreerd', 'Gebruiksvriendelijk', 'Gamification', 'Nederlandse support'],
    cons: ['Minder design vrijheid'],
    features: ['E-learning modules', 'Forum', 'Mobiele app', 'Drip-content'],
    specifications: [{ label: 'Type', value: 'Community & E-learning' }, { label: 'App', value: 'PWA' }],
    pricingTiers: [{ name: 'Start', price: '€19/mnd', features: ['Max 100 leden'] }, { name: 'Grow', price: '€49/mnd', features: ['Onbeperkt'] }],
    targetAudience: ['Cursus makers', 'Verenigingen', 'Bedrijven'],
    faq: [{ question: 'Eigen domein?', answer: 'Ja, dat kan.' }],
    updatedAt: '10 oktober 2024'
  },
  {
    id: 'canva-01',
    slug: 'canva-pro',
    title: 'Canva Pro',
    description: 'Design tool voor niet-designers. Maak professionele visuals, social media posts en presentaties.',
    seoDescription: 'Canva Pro Review: De ultieme design tool voor ondernemers en marketeers.',
    category: Category.DESIGN,
    type: ItemType.APP,
    contentType: ContentType.TOOL,
    priceLabel: '€11,99/mnd',
    rating: 4.8,
    provider: 'Canva',
    imageUrl: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?auto=format&fit=crop&w=1280&q=80',
    affiliateLink: 'https://www.canva.com/pro',
    tags: ['design', 'social media', 'graphics', 'branding', 'tool'],
    pros: ['Extreem gebruiksvriendelijk', 'Enorme template bibliotheek', 'Team samenwerking', 'Brand Kit'],
    cons: ['Beperkte geavanceerde opties'],
    features: ['100+ miljoen stock fotos', 'Brand Kit', 'Background remover', 'Magic Resize'],
    targetAudience: ['Ondernemers zonder design achtergrond', 'Social media managers'],
    updatedAt: '1 november 2024'
  },
  {
    id: 'notion-01',
    slug: 'notion',
    title: 'Notion',
    description: 'Alles-in-een workspace voor notities, projectmanagement, databases en documentatie.',
    seoDescription: 'Notion Review: De ultieme productiviteitstool voor teams en individuen.',
    category: Category.PRODUCTIVITY,
    type: ItemType.APP,
    contentType: ContentType.TOOL,
    priceLabel: 'Gratis / €8/mnd',
    rating: 4.7,
    provider: 'Notion Labs',
    imageUrl: 'https://images.unsplash.com/photo-1611224923853-80b023f02d71?auto=format&fit=crop&w=1280&q=80',
    affiliateLink: 'https://www.notion.so',
    tags: ['productiviteit', 'notities', 'projectmanagement', 'workspace', 'tool'],
    pros: ['Extreem flexibel', 'Gratis tier bruikbaar', 'Sterke database functionaliteit', 'Minimalistische interface'],
    cons: ['Steile leercurve'],
    features: ['Linked databases', 'Templates', 'Team workspaces', 'API integraties', 'AI functies'],
    targetAudience: ['Freelancers', 'Start-up teams', 'Content creators'],
    updatedAt: '5 november 2024'
  }
];

// Combined items for backward compatibility
export const STATIC_ITEMS: GrowthItem[] = [...STATIC_TOOLS, ...STATIC_COURSES];

export const STATIC_BLOG_POSTS: BlogPost[] = [
  {
    id: 'blog-seo-101',
    slug: 'wat-is-seo',
    title: 'Wat is SEO? Een complete gids voor beginners in 2024',
    seoTitle: 'Wat is SEO? Complete Beginnersgids 2024 | Writgo',
    metaDescription: 'Leer de basisprincipes van SEO en ontdek hoe je hoger scoort in Google.',
    excerpt: 'Leer de basisprincipes van zoekmachineoptimalisatie (SEO) en ontdek hoe je hoger kunt scoren in Google.',
    content: '<h2>Wat betekent SEO precies?</h2><p>SEO staat voor Search Engine Optimization. Het is het proces van het optimaliseren van je website om hoger te scoren in de organische zoekresultaten.</p><h2>De 3 pijlers van SEO</h2><ul><li><strong>Techniek:</strong> Zorg dat zoekmachines je website kunnen crawlen.</li><li><strong>Content:</strong> Creeer waardevolle content.</li><li><strong>Autoriteit:</strong> Bouw backlinks op.</li></ul>',
    author: 'Writgo Redactie',
    date: '25 Okt 2024',
    imageUrl: 'https://images.unsplash.com/photo-1562577309-2592ab84b1bc?auto=format&fit=crop&w=800&q=80',
    category: Category.MARKETING,
    tags: ['seo', 'google', 'zoekmachine', 'marketing', 'beginners'],
    readTime: '6 min',
    keyTakeaways: ['SEO is het optimaliseren voor onbetaalde zoekresultaten.', 'De drie pijlers zijn Techniek, Content en Autoriteit.'],
    status: 'published',
    publishedAt: '2024-10-25T10:00:00Z',
    viewCount: 1250,
    seoScore: 85
  },
  {
    id: 'blog-aff-cursus-best',
    slug: 'beste-affiliate-marketing-cursus',
    title: 'De Beste Affiliate Marketing Cursus van Nederland',
    seoTitle: 'Beste Affiliate Marketing Cursus Nederland 2024',
    metaDescription: 'Vergelijk de beste affiliate marketing cursussen in Nederland.',
    excerpt: 'Wil je starten met affiliate marketing? We vergelijken de populairste cursussen.',
    content: '<h2>Waar moet je op letten bij een Cursus?</h2><p>Een goede cursus leert je meer dan alleen hoe je een link plaatst.</p>',
    author: 'Sander de Vries',
    date: '22 Okt 2024',
    imageUrl: 'https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?auto=format&fit=crop&w=800&q=80',
    category: Category.MARKETING,
    tags: ['affiliate', 'marketing', 'cursus', 'online geld verdienen'],
    readTime: '8 min',
    status: 'published',
    publishedAt: '2024-10-22T14:00:00Z',
    viewCount: 890,
    seoScore: 78
  },
  {
    id: 'blog-bitvavo-rev',
    slug: 'bitvavo-review',
    title: 'Bitvavo Review 2024: Is dit de Beste Crypto Exchange?',
    seoTitle: 'Bitvavo Review 2024: Beste Crypto Exchange?',
    metaDescription: 'Complete Bitvavo review: kosten, veiligheid en gebruiksvriendelijkheid.',
    excerpt: 'Bitvavo is de grootste crypto exchange van Nederland. We onderzoeken kosten en veiligheid.',
    content: '<h2>Wat is Bitvavo?</h2><p>Bitvavo is een Nederlandse crypto exchange waar je 200+ cryptocurrencies kunt kopen.</p>',
    author: 'Emma Jansen',
    date: '18 Okt 2024',
    imageUrl: 'https://images.unsplash.com/photo-1621419739883-9a775cf35534?auto=format&fit=crop&w=800&q=80',
    category: Category.FINANCE,
    tags: ['crypto', 'bitvavo', 'bitcoin', 'exchange', 'beleggen'],
    readTime: '7 min',
    status: 'published',
    publishedAt: '2024-10-18T11:00:00Z',
    viewCount: 2100,
    seoScore: 82
  },
  {
    id: 'blog-extra-geld',
    slug: 'extra-geld-verdienen-naast-je-baan',
    title: '12 Realistische Manieren om Extra Geld te Verdienen Naast Je Baan',
    seoTitle: '12 Manieren Extra Geld Verdienen Naast Je Baan 2024',
    metaDescription: 'Ontdek 12 realistische side hustles om extra geld te verdienen naast je werk.',
    excerpt: 'Zoek je een manier om je inkomen aan te vullen? Ontdek 12 concrete side hustles.',
    content: '<h2>Waarom een Side Hustle?</h2><p>Een extra inkomstenbron geeft financiele ademruimte.</p>',
    author: 'Writgo Redactie',
    date: '15 Okt 2024',
    imageUrl: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=800&q=80',
    category: Category.FINANCE,
    tags: ['side hustle', 'extra geld', 'bijverdienen', 'freelance'],
    readTime: '9 min',
    status: 'published',
    publishedAt: '2024-10-15T09:00:00Z',
    viewCount: 3200,
    seoScore: 90
  }
];
